# Generated by ChatGPT

import requests
import time
from concurrent.futures import ThreadPoolExecutor

URL = "http://3.25.221.126:8080/detect-image"
IMAGE_PATH = "img.png"
CONCURRENT = 10          # number of simultaneous workers
DURATION = 300          # run for 5 minutes (in seconds)

with open(IMAGE_PATH, "rb") as f:
    IMAGE_BYTES = f.read()

def send_request(i):
    files = {"file": (IMAGE_PATH, IMAGE_BYTES, "image/jpeg")}
    try:
        resp = requests.post(URL, files=files, timeout=30)
        print(f"[{i}] {resp.status_code} -> {resp.text[:80]}...")
    except Exception as e:
        print(f"[{i}] Error: {e}")

def worker(worker_id, stop_time):
    i = 0
    while time.time() < stop_time:
        send_request(f"{worker_id}-{i}")
        i += 1

if __name__ == "__main__":
    stop_time = time.time() + DURATION
    start = time.time()

    with ThreadPoolExecutor(max_workers=CONCURRENT) as executor:
        for w in range(CONCURRENT):
            executor.submit(worker, w, stop_time)

    print(f"Completed load test in {time.time()-start:.2f} seconds")
